# Generated by Django 5.2.6 on 2025-09-12 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('id_lender', models.CharField(max_length=100)),
                ('id_monitor', models.CharField(max_length=100)),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('VENCIDO', 'VENCIDO')], default='ABIERTO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('code', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MONITOR', 'MONITOR')], default='MONITOR', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='invook_admi_usernam_2a0727_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consum',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('id_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.administrativeuser')),
                ('id_lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.lender')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('serial', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('state', models.CharField(choices=[('BUENO', 'BUENO'), ('FUNCIONAL', 'FUNCIONAL'), ('DAÑO_LEVE', 'DAÑO_LEVE'), ('NO_FUNCIONA', 'NO_FUNCIONA'), ('PERDIDO', 'PERDIDO')], default='BUENO', max_length=20)),
                ('available', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('NO_DISPONIBLE', 'NO_DISPONIBLE')], default='DISPONIBLE', max_length=20)),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.hardwaretype')),
            ],
        ),
        migrations.CreateModel(
            name='LoanHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.hardware')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.loan')),
            ],
            options={
                'unique_together': {('loan', 'hardware')},
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='hardware',
            field=models.ManyToManyField(related_name='loans', through='invook.LoanHardware', to='invook.hardware'),
        ),
        migrations.CreateModel(
            name='ConsumSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('consum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.consum')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.supply')),
            ],
            options={
                'unique_together': {('consum', 'supply')},
            },
        ),
        migrations.AddField(
            model_name='consum',
            name='supplies',
            field=models.ManyToManyField(related_name='consumed_supplies', through='invook.ConsumSupply', to='invook.supply'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supply_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invook.supplytype'),
        ),
    ]
