# Generated by Django 5.2.6 on 2025-09-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='id_lender',
            new_name='lender',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='id_monitor',
            new_name='monitor',
        ),
    ]
