# Generated by Django 5.2.6 on 2025-09-13 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0002_rename_id_lender_loan_lender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='lender',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monitor',
        ),
        migrations.AddField(
            model_name='loan',
            name='id_lender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='invook.lender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='id_monitor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='invook.administrativeuser'),
            preserve_default=False,
        ),
    ]
