# Generated by Django 5.2.6 on 2025-09-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0003_remove_loan_lender_remove_loan_monitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='hardware_type',
            new_name='hardware_type_id',
        ),
    ]
