# Generated by Django 5.2.6 on 2025-09-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0004_rename_hardware_type_hardware_hardware_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='hardware_type_id',
            new_name='hardware_type',
        ),
    ]
