# Generated by Django 5.2.6 on 2025-09-18 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0005_rename_hardware_type_id_hardware_hardware_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='administrativeuser',
            name='invook_admi_usernam_2a0727_idx',
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
