# Generated by Django 5.2.6 on 2025-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0006_remove_administrativeuser_invook_admi_usernam_2a0727_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhardware',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
