# Generated by Django 5.2.6 on 2025-09-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0007_loanhardware_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
