# Generated by Django 5.2.6 on 2025-09-19 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0008_alter_supply_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
