# Generated by Django 5.2.6 on 2025-09-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0009_alter_consum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumsupply',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
