# Generated by Django 5.2.6 on 2025-09-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0010_alter_consumsupply_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consum',
            name='supplies',
            field=models.ManyToManyField(through='invook.ConsumSupply', to='invook.supply'),
        ),
        migrations.AlterField(
            model_name='consumsupply',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
