# Generated by Django 5.2.6 on 2025-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0012_administrativeuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhardware',
            name='return_state',
            field=models.CharField(blank=True, choices=[('BUENO', 'BUENO'), ('FUNCIONAL', 'FUNCIONAL'), ('DAÑO_LEVE', 'DAÑO_LEVE'), ('NO_FUNCIONA', 'NO_FUNCIONA'), ('PERDIDO', 'PERDIDO')], max_length=20, null=True),
        ),
    ]
