# Generated by Django 5.2.6 on 2025-09-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0013_alter_administrativeuser_options_and_more'),
        ('invook', '0013_loanhardware_return_state'),
    ]

    operations = [
    ]
