# Generated by Django 5.2.6 on 2025-09-27 13:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0014_merge_20250927_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Profile',
                'verbose_name_plural': 'Administrative Profiles',
                'db_table': 'administrative_profile',
            },
        ),
    ]
