# Generated by Django 5.2.6 on 2025-09-28 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0016_create_admin_monitor_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhardware',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
