# Generated by Django 5.2.7 on 2025-10-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0018_emaillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
