# Generated by Django 5.2.7 on 2025-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0020_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplytype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
