# Generated by Django 5.2.7 on 2025-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0021_hardwaretype_active_supplytype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
