# Generated by Django 5.2.7 on 2025-10-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0022_hardware_active_supply_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
