# Generated by Django 5.2.7 on 2025-11-05 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invook', '0023_lender_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhardware',
            name='loaned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
